export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const VIEW_ARTICLES_ERROR = 'VIEW_ARTICLES_ERROR';
export const VIEW_ARTICLES = 'VIEW_ARTICLES';
export const GETTING_ARTICLES = 'GETTING_ARTICLES';
