export const CREATE_USER = 'CREATE_USER';
export const CREATE_USER_ERROR = 'CREATE_USER_ERROR';
export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const VIEW_ALL_ARTICLES = 'VIEW_ALL_ARTICLES';
export const FETCHING_ARTICLES = 'FETCHING_ARTICLES';
export const VIEW_ALL_ARTICLES_ERROR = 'VIEW_ALL_ARTICLES_ERROR';
